# Generated by Django 3.0 on 2024-04-09 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusers',
            name='designation',
        ),
        migrations.AddField(
            model_name='customusers',
            name='course',
            field=models.CharField(choices=[('F', 'Front-end Software Development'), ('B', 'Backend Software Development'), ('C', 'Cloud Computing'), ('I', 'Internet of Things'), ('M', 'Machine Learning')], default=None, max_length=1),
            preserve_default=False,
        ),
    ]
