# Generated by Django 3.0 on 2024-04-09 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20240409_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusers',
            name='estimated_fees',
            field=models.CharField(default='$14000', max_length=6),
        ),
    ]
