# Generated by Django 3.0 on 2024-04-09 20:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customusers_estimated_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusers',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
    ]
