# Generated by Django 3.0 on 2024-04-10 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customusers_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusers',
            name='course',
            field=models.CharField(choices=[('Front-end Software Development', 'Front-end Software Development'), ('Backend Software Development', 'Backend Software Development'), ('Cloud Computing', 'Cloud Computing'), ('Internet of Things', 'Internet of Things'), ('Machine Learning', 'Machine Learning')], max_length=100),
        ),
    ]
