# Generated by Django 3.2.12 on 2024-04-15 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20240409_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusers',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
